### PR TITLE
Make GitHub detect *.fsb as Forth.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
Hello,

Please merge this, if you'd like GitHub to detect your `.fsb` files as Forth.

Thanks!

### CODE REVIEW

**Comment by programandala-net** [comment]
En/Je/On 2015-11-26 22:25, Lars Brinkhoff escribió / skribis / wrote :

>    Please merge this, if you'd like GitHub to detect your
>    .fsb files as Forth.

Done, thank you! I was about to investigate that problem.

I use .fsb instead of .fs because the files are in a special format,
required by a converter I wrote. I'm publishing it on GitHub.

## 

Marcos Cruz
http://programandala.net

**Comment by larsbrinkhoff** [comment]
That's great!  I'm trying to improve visibility of Forth on GitHub.  The more, the merrier!

**Comment by programandala-net** [comment]
En/Je/On 2015-11-27 11:03, Lars Brinkhoff escribió / skribis / wrote :

> I'm trying to improve visibility of Forth on GitHub. The more, the
> merrier!

Great! I want to co-operate on anything related to promoting Forth.  As
of GitHub, I will contribute with all my code (the second project is
already uploaded, an the third one is on its way).  I have a lot of
Forth projects, either already published on my website or not, and I've
started preparing them in order to publish them on GitHub.

So far I've always used my own local tools for development (even my
website is built with a static website maker I wrote in Forth, not
published yet).

But the other day, at the same time you suggested me to publish Afera on
GitHub after my announce in clf, also my younger brother suggested to
start using git, in order to co-operate with him on a common project. So
it seemed the right time to start...

## 

Marcos Cruz
http://programandala.net

**Comment by larsbrinkhoff** [comment]
How about I add you to the ForthHub/Libraries team, and you can add your tools (and libraries) yourself if you like?

**Comment by programandala-net** [comment]
En/Je/On 2015-11-28 11:29, Lars Brinkhoff escribió / skribis / wrote :

> How about I add you to the ForthHub/Libraries team, and you can add
> your tools (and libraries) yourself if you like?

OK. But I'm just starting to know how all this thing works... I need
more time to become familiar with.

## 

Marcos Cruz
http://programandala.net

**Comment by larsbrinkhoff** [comment]
Sure, take your time!

**Pull request merged**
